USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE GLUEDB;

CREATE OR REPLACE STORAGE INTEGRATION GLUE_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470957633639:role/snowflakerole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://dea-gluebucket/data/');
    
    DESC INTEGRATION GLUE_S3_INT;

CREATE OR REPLACE STAGE GLUEDB.PUBLIC.GLUE_S3_STAGE
STORAGE_INTEGRATION = GLUE_S3_INT
URL= 's3://dea-gluebucket/data/';

    ls @GLUEDB.PUBLIC.GLUE_S3_STAGE;

CREATE OR REPLACE TABLE GLUEDB.PUBLIC.COUNTRY_DETAILS_CP
(
DATA VARIANT
);
-- source
select * from GLUEDB.PUBLIC.COUNTRY_DETAILS_CP;
-- raw data
select * from GLUEDB.RAW.COUNTRY_DETAILS_RAW;
-- transformed data (json to row flattened data)
select * from GLUEDB.TRANSFORM.COUNTRY_DETAILS_TRANSFORM;

SELECT DISTINCT COUNTRY_CONTINENT_NAME FROM GLUEDB.TRANSFORM.COUNTRY_DETAILS_TRANSFORM;
-- final data

CREATE OR REPLACE DATABASE GLUEDB_PRODUCTION;
USE GLUEDB_PRODUCTION;
SELECT 
    table_name, 
    row_count
FROM 
    information_schema.tables 
WHERE 
    table_catalog = 'GLUEDB_PRODUCTION'
    AND table_type = 'BASE TABLE'
ORDER BY 
    table_name;